### PR TITLE
Initialized the Sentence Token Position variable

### PR DESCRIPTION
**Pull request by Ask149**
File Requested: Baby6.1/include/c_Sentence.h
Purpose: Initializing the int_Sentence_Token_Position variable to '0', as it is referenced in the future once. Hi, I am understanding your project and I really wish to start contributing to your project. Could you please allow me to contribute to your project? Thanks!.

### CODE REVIEW

**Comment by Ask149** [comment]
I'll surely try to maintain your code of conduct.

**Comment by Daniel061** [comment]
Thank you for your interest in this project. I welcome your input.
Remember, I would like to keep the code as readable as possible.
Thank you again and Welcome to the project.

**Comment by Ask149** [comment]
Sure, Thanks!
I'll keep that in mind.

**Comment by Daniel061** [comment]
Also, I read the purposed change. That's a good catch but the form of initialization is c++11. I have not yet enabled C++11 in my Code::Blocks. Do you see a benefit?

**Comment by Ask149** [comment]
> Also, I read the purposed change. That's a good catch but the form of initialization is c++11. I have not yet enabled C++11 in my Code::Blocks. Do you see a benefit?

I would suggest to upgrade to C++11 because later on you will probably need asynchronous proceesing and multithreading facilities which are available in C++11 onwards. Do you want me to scale down to C++ ?

**Comment by Daniel061** [comment]
No, please do not scale down. I like the readability of the initialization method. 
I will enable C++11 on my Code::Blocks IDE.
Thank You.

**Pull request merged**
